name: AppEngine Deployment
# For this to work, you must verify the App Engine Admin API is enabled.
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieving the repo
        uses: actions/checkout@v3
      - name: Preparing GCloud Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}' # You must run base64 ./gcp_creds.json, then paste the output into the secrets area in your repo settings.
      - name: Setup GCloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: "facts-sender"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        env:
          APPLICATION_CREDENTIALS: ${{ secrets.APPLICATION_CREDENTIALS }}
        run: |
          echo $APPLICATION_CREDENTIALS > ~/facts-sender-owner.json
          pip install pytest
          python -m pytest tests/
      - name: Run deployment
        if: success()
        run: "gcloud app deploy ./fact_sender_app.yaml --quiet"
